version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: chat_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "mysql://root:your_mysql_root_password@mysql:3306/chat_app"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://chat-app.ingsun.co/backend"
      NEXTAUTH_SECRET: "your_generated_secret"
      NEXTAUTH_URL: "http://localhost:3000"
      REACT_APP_API_BASE_URL: "https://chat-app.ingsun.co/backend"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
